nombre = input("¿Cúal es tu nombre?")
apellido = input("¿Cúal es tu apellido?")
seccion = input("Indica tu código y sección")
sede = input("¿Cúal es tu sede?")
print("La alumna " + nombre, apellido + " es estudiante de " + seccion + " de la sede " + sede)